config/routes.rb
Rails.application.routes.draw do
  root "blogs#index"
  resources :blogs
  get "/notFound", to: "blogs#notFound"
  get "/archived-blogs", to:"blogs#archivedBlogs"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
  include Visible
  validates :title, presence: true,uniqueness: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = ['public', 'private', 'archived']

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  class_methods do
    def public_count
      where(status: 'public').count
    end
    def private_count
      where(status:'private').count
    end
    def archived_count
      where(status:'archived').count
    end
    def total_count
      private_count+public_count+archived_count
    end
  end

  def archived?
    status == 'archived'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs = Blog.order(created_at: :desc)
  end

  def show
    @blog = Blog.find(params[:id])
    rescue ActiveRecord::RecordNotFound
    redirect_to :controller => "blogs", :action => "notFound"
    return
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(article_params)
    if @blog.save
      redirect_to @blog
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
    if @blog.update(article_params)
      redirect_to @blog
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy
    redirect_to blogs_path, status: :see_other
  end

  def archivedBlogs
    @blogs = Blog.where(status:'archived').order(created_at: :desc)
  end

  def notFound
  end

  private
  def article_params
    params.required(:blog).permit(:title,:body,:status)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<div class="container">
<%= form_with model: blog do |form| %>
  <div class="form-group">
    <%= form.label :title %>
    <br>
    <%= form.text_field :title, :class=>"form-control"%>
    <% blog.errors.full_messages_for(:title).each do |message| %>
      <div class="text-danger"><%= message %></div>
    <% end %>
  </div>
  <div class="form-group">
    <%= form.label :body %>
    <br>
    <%= form.text_area :body,:class=>"form-control" %>
    <% blog.errors.full_messages_for(:body).each do |message| %>
      <div  class="text-danger"><%= message %></div>
    <% end %>
  </div>
  <div class="form-group">
    <%= form.label :status %><br>
    <%= form.select :status, ['public', 'private', 'archived'], selected: @blog.status,:class=>"form-control" %>
  </div>
  <div>
    <%= form.submit :class=>"btn btn-success" %>
  </div>
  <div>

  </div>
    </div>
<% end %>

app/views/blogs/archivedBlogs.html.erb
<h1 class="text-center">Archieved Blogs</h1>
<!--<p>We have total <%#= Blog.public_count + Blog.private_count + Blog.archived_count %> blogs.</p>-->
<div class="container">
  <div>
<p>We have total <%= Blog.archived_count %> archieved
  <%if Blog.total_count == 1 || Blog.total_count == 0 %>blog
  <%else %>
    blogs
  <%end %>
</p>
<ul>
  <% @blogs.each do |blog| %>
    <li>
      <a href="<%= blog_path(blog) %>">
        <%= blog.title %>
      </a>
    </li>
  <% end %>
</ul>
  </div>
<%= link_to "New Blog", new_blog_path, :class => "btn btn-success btn-sm" %>
<%= link_to "Back to List", blogs_path, :class => "btn btn-primary btn-sm" %></div>

app/views/blogs/edit.html.erb
<h1  class="text-center">Edit Article</h1>

<%= render "form", blog: @blog %>

app/views/blogs/index.html.erb
<h1 class="text-center">All Blogs</h1>
<!--<p>We have total <%#= Blog.public_count + Blog.private_count + Blog.archived_count %> blogs.</p>-->
<div class="container">
<div>
  <p>We have total <%= Blog.total_count %>
  <%if Blog.total_count == 1 || Blog.total_count == 0 %>blog
    <%else %>
    blogs
    <%end %>
    </p>
<ul>
  <% @blogs.each do |blog| %>
    <%# unless blog.archived?%>
  <li>
    <a href="<%= blog_path(blog) %>">
      <%= blog.title %>
    </a>
  </li>
      <%#end %>
  <% end %>
</ul>
</div>

<%= link_to "New Blog", new_blog_path,  :class => "btn btn-success btn-sm" %>
  <% if Blog.archived_count > 0 %>
    <%= link_to "Archived Blogs", archived_blogs_path,  :class => "btn btn-primary btn-sm" %>
<%end %>
</div>

app/views/blogs/new.html.erb
<h1 class="text-center">New Blog</h1>

<%= render "form", blog: @blog %>

app/views/blogs/notFound.html.erb
<h1>Sorry, Blog is not found</h1>

app/views/blogs/show.html.erb
<div class="container">
  <h1>
    <%= @blog.title %>
  </h1>
  <p>
    <%= @blog.body %>
  </p>
  <p>
    <b>Status</b> : <%= @blog.status %>
  </p>
  <div class="row">
  <%= link_to "Edit", edit_blog_path(@blog), :class=>"col-md-2 btn btn-success" %>
    <%= button_to 'Delete',@blog, method: :delete, :class=>"col-md-2 btn btn-danger" , :onclick=>"return confirm('Are you sure you want to delete this item')" %>
    <%= link_to "Back to List", blogs_path,:class=>"col-md-2 btn btn-info"  %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>